### ISSUE TITLE
New Logo/Icon Proposal

### ISSUE THREAD

**Issue by mansya** [iTimeTraveler/Android-WheelPicker#1]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by iTimeTraveler** [comment]
@mansya Wow, honestly I can't wait, That's my pleasure to accept your gift, This is a most welcome, Thank you. 😄 🥇

**Comment by mansya** [comment]
Hi sir, I have design logo for this project. what do you think ? do you like it ? if yes, which one do you like it ? 
![wheel picker](https://user-images.githubusercontent.com/33461607/45943518-cb712600-c010-11e8-8d70-91db31d56e4e.png)

sorry for the late response sir.

**Comment by iTimeTraveler** [comment]
@mansya the first and second are OK, I think. Thanks for you again.

**Comment by mansya** [comment]
hi sir. I choose the first for you. the reason is the first one looks more attractive and the color is almost the same as the color of the application. and I have sent you [**pull requests.**](https://github.com/iTimeTraveler/Android-WheelPicker/pull/2) please check.
and for all the files you can access them here. [**Download**](https://drive.google.com/open?id=10QLoLLtmFVNnuVjqobH-lj9QJ9PhU6hL)

**Comment by iTimeTraveler** [comment]
@mansya Thank you so much, and Good luck to you.
