### ISSUE TITLE
How to change Selected item Text color. issue with dark mode enabled

### ISSUE THREAD

**Issue by parmarkamlesh** [iTimeTraveler/Android-WheelPicker#7]
![image](https://user-images.githubusercontent.com/31653703/119087799-55255b80-ba25-11eb-8786-bda0e5ee6bdb.png)

**Comment by iTimeTraveler** [comment]
@parmarkamlesh 每个选项其实都是一个View，就像ListView或者RecycleView里的ViewHolder，你可以找到这个View修改一下就行，或者自定义一个View

**Comment by parmarkamlesh** [comment]
@iTimeTraveler Yeah, thank i solved by changing text color of item in individual viewHolder,thanks
